/**
 * E-Signature Page - Step 4 (Final) of Checkout Flow
 *
 * This page initiates the e-signature process and monitors signing status.
 * It demonstrates a polling pattern for tracking asynchronous backend operations.
 *
 * Flow:
 * 1. Call backend to start signing process
 * 2. Backend creates envelope with e-sign provider and returns signing URL
 * 3. Open signing URL in new tab for user to sign
 * 4. Poll contract status every 5 seconds
 * 5. When status becomes 'signed', show success and download link
 * 6. Stop polling after 2 minutes with timeout message
 *
 * Architecture:
 * - Signing happens in external tab (e-sign provider UI)
 * - Backend receives webhook when signing completes
 * - Frontend polls to detect status change (no websockets needed)
 * - Polling is resilient to errors and has max duration
 *
 * Security considerations:
 * - Contract ID is validated backend before starting signing
 * - Signing URL is generated by e-sign provider (stub in dev)
 * - Backend webhook verification ensures only trusted status updates
 * - Status polling prevents user from skipping signature
 * - Timeout prevents infinite polling (resource exhaustion)
 * - Cleanup on unmount prevents memory leaks
 */

"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import Stepper from "@/src/components/Stepper";
import {
  startSigning,
  getContract,
  getSignedPdfUrl,
} from "@/src/lib/api";
import { getCheckoutState, clearCheckoutState } from "@/src/lib/checkout-state";
import type { Contract, SigningStartResponse } from "@/src/lib/types";

/**
 * Polling configuration constants.
 * These control the status polling behavior.
 */
const POLL_INTERVAL_MS = 5000; // Poll every 5 seconds
const MAX_POLL_COUNT = 24;     // Max 24 polls = 2 minutes

export default function SignPage() {
  const router = useRouter();
  
  // State management
  const [signingData, setSigningData] = useState<SigningStartResponse | null>(null);
  const [contract, setContract] = useState<Contract | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [polling, setPolling] = useState(false);
  
  /**
   * Refs for polling logic.
   * - pollingTimeoutRef: Reference to setTimeout for cancellation
   * - pollCountRef: Track number of polls for timeout
   * - pollContractRef: Function reference for recursive polling
   *
   * Using refs instead of state prevents unnecessary re-renders
   * and maintains stable references across effect executions.
   */
  const pollingTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const pollCountRef = useRef(0);
  const pollContractRef = useRef<((contractId: string) => Promise<void>) | null>(null);

  /**
   * Initialize signing process and start status polling.
   * Runs once on component mount.
   */
  useEffect(() => {
    /**
     * Polls the contract status to detect signing completion.
     * This function calls itself recursively via setTimeout to implement polling.
     *
     * Polling stops when:
     * 1. Contract status becomes 'signed' (success)
     * 2. Poll count reaches MAX_POLL_COUNT (timeout after 2 minutes)
     * 3. Component unmounts (cleanup function cancels timeout)
     *
     * Error handling:
     * - Network errors don't stop polling (continues to next attempt)
     * - Logs errors to console for debugging
     * - Still respects MAX_POLL_COUNT to prevent infinite loops
     *
     * @param contractId - UUID of contract to poll
     *
     * Security notes:
     * - Uses contract ID from trusted state (saved during preview)
     * - Backend validates contract exists on each poll
     * - Prevents status manipulation by user (backend is source of truth)
     * - Timeout prevents resource exhaustion from infinite polling
     */
    const pollContract = async (contractId: string) => {
      try {
        const contractData = await getContract(contractId);
        setContract(contractData);

        // Success condition: Stop polling when signed
        if (contractData.status === "signed") {
          setPolling(false);
          return;
        }

        // Timeout condition: Stop after 2 minutes (24 * 5s = 120s)
        pollCountRef.current += 1;
        if (pollCountRef.current >= MAX_POLL_COUNT) {
          setPolling(false);
          setError(
            "Signing process is taking longer than expected. Please check back later.",
          );
          return;
        }

        // Schedule next poll after interval
        pollingTimeoutRef.current = setTimeout(
          () => pollContract(contractId),
          POLL_INTERVAL_MS,
        );
      } catch (err: unknown) {
        // Log error but continue polling
        // Network blips shouldn't stop the entire process
        console.error("Polling error:", err);
        
        pollCountRef.current += 1;
        if (pollCountRef.current < MAX_POLL_COUNT) {
          pollingTimeoutRef.current = setTimeout(
            () => pollContract(contractId),
            POLL_INTERVAL_MS,
          );
        }
      }
    };
    
    // Store function reference for use in initialization
    pollContractRef.current = pollContract;
    
    /**
     * Initializes the signing process.
     *
     * Steps:
     * 1. Validate contract ID exists (guard)
     * 2. Call backend to start signing (creates envelope, gets URL)
     * 3. Begin status polling immediately
     *
     * The signing URL is shown to user but polling starts right away
     * in case they sign very quickly.
     */
    const initializeSigning = async () => {
      const state = getCheckoutState();

      /**
       * Guard: Ensure contract exists from previous step.
       * If not, redirect to start (shouldn't happen in normal flow).
       */
      if (!state.contractId) {
        router.push("/checkout/offer");
        return;
      }

      try {
        // Start signing process on backend
        const signingResponse = await startSigning(state.contractId);
        setSigningData(signingResponse);
        setLoading(false);
        
        // Begin polling immediately
        setPolling(true);
        pollCountRef.current = 0;
        if (pollContractRef.current) {
          pollContractRef.current(state.contractId);
        }
      } catch (err: unknown) {
        setError(
          err instanceof Error ? err.message : "Failed to start signing process",
        );
        setLoading(false);
      }
    };

    initializeSigning();

    /**
     * Cleanup function: Cancel polling on unmount.
     * Prevents memory leaks and unnecessary API calls.
     */
    return () => {
      if (pollingTimeoutRef.current) {
        clearTimeout(pollingTimeoutRef.current);
      }
    };
  }, [router]);

  /**
   * Clears checkout state and returns to beginning.
   * Allows user to start a new contract flow.
   */
  const handleStartOver = () => {
    clearCheckoutState();
    router.push("/checkout/offer");
  };

  /**
   * Opens the signed PDF in a new tab for download.
   * Only available after contract status becomes 'signed'.
   *
   * Security note: PDF URL is constructed client-side but
   * backend validates contract is signed before serving file.
   */
  const handleDownloadSignedPdf = () => {
    if (contract) {
      window.open(getSignedPdfUrl(contract.id), "_blank");
    }
  };

  // Loading state: Show while initializing signing
  if (loading) {
    return (
      <div>
        <Stepper currentStep={4} />
        <div className="flex justify-center items-center py-12">
          <div className="text-gray-600">Initializing signing process...</div>
        </div>
      </div>
    );
  }

  // Error state: Show if signing initialization failed
  if (error && !signingData) {
    return (
      <div>
        <Stepper currentStep={4} />
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
          <strong>Error:</strong> {error}
        </div>
        <div className="mt-4">
          <button
            onClick={() => router.push("/checkout/preview")}
            className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            Back
          </button>
        </div>
      </div>
    );
  }

  // Status helpers for conditional rendering
  const isSigned = contract?.status === "signed";
  const isAwaitingSignature = contract?.status === "awaiting_signature";

  // Main render: Show signing interface and status
  return (
    <div>
      <Stepper currentStep={4} />

      <div className="bg-white rounded-lg shadow-sm p-6">
        <h1 className="text-2xl font-bold mb-6">Sign Contract</h1>

        {/* Signing URL Section */}
        {signingData && (
          <div className="mb-6 p-4 bg-blue-50 rounded-lg">
            <h2 className="font-semibold text-lg mb-3">Ready to Sign</h2>
            <p className="text-gray-700 mb-4">
              Click the button below to open the signing page in a new tab.
            </p>
            {/*
              Security note: Opens external signing URL in new tab.
              - URL is generated by e-sign provider (trusted source)
              - target="_blank" with noopener prevents window.opener access
              - User completes signing in separate context
            */}
            <button
              onClick={() => window.open(signingData.signing_url, "_blank")}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              Open Signing Page
            </button>
          </div>
        )}

        {/* Status Display Section */}
        <div className="mb-6 p-4 bg-gray-50 rounded-lg">
          <h2 className="font-semibold text-lg mb-3">Contract Status</h2>
          
          <div className="flex items-center space-x-3">
            {/* Polling indicator: spinning circle */}
            {polling && (
              <div className="w-5 h-5 border-2 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
            )}
            <div>
              <span className="font-medium">Status: </span>
              {/* Status badge with color coding */}
              <span
                className={`inline-block px-3 py-1 rounded ${
                  isSigned
                    ? "bg-green-100 text-green-800"      // Success: Green
                    : isAwaitingSignature
                      ? "bg-yellow-100 text-yellow-800"  // In progress: Yellow
                      : "bg-gray-100 text-gray-800"      // Unknown: Gray
                }`}
              >
                {contract?.status || signingData?.status || "unknown"}
              </span>
            </div>
          </div>

          {polling && (
            <p className="text-sm text-gray-600 mt-2">
              Checking for signature completion...
            </p>
          )}
        </div>

        {/* Success Message (shown when signed) */}
        {isSigned && (
          <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg">
            <h2 className="font-semibold text-lg text-green-800 mb-2">
              ✓ Contract Signed Successfully!
            </h2>
            <p className="text-green-700 mb-4">
              Your contract has been signed and is now active.
            </p>
            <button
              onClick={handleDownloadSignedPdf}
              className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              Download Signed PDF
            </button>
          </div>
        )}

        {/*
          Development Helper: Stub webhook hint.
          Only shown in non-production environments.
          
          In stub mode, signing doesn't actually complete until webhook
          is manually triggered. This helps developers test the flow.
          
          Security: process.env.NODE_ENV is build-time constant,
          so this code is eliminated in production builds.
        */}
        {isAwaitingSignature && process.env.NODE_ENV !== "production" && (
          <div className="mb-6 p-3 bg-yellow-50 border border-yellow-200 rounded text-sm text-yellow-800">
            <strong>Dev Note:</strong> To simulate signing completion, the
            operator can trigger the stub webhook endpoint.
          </div>
        )}

        {/* Timeout Warning (shown if polling times out) */}
        {error && (
          <div className="mb-6 p-4 bg-orange-50 border border-orange-200 text-orange-700 rounded">
            {error}
          </div>
        )}

        {/* Action buttons */}
        <div className="flex justify-between">
          <button
            onClick={handleStartOver}
            className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            Start Over
          </button>
          {!isSigned && (
            <button
              onClick={() => router.push("/checkout/preview")}
              className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              Back to Preview
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
