"""add_counterparties_and_contract_fk

Revision ID: 1e80718f58ed
Revises: 0b221ccc449c
Create Date: 2025-12-25 08:42:03.352210

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e80718f58ed"
down_revision: Union[str, Sequence[str], None] = "0b221ccc449c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counterparties",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_counterparties_email", "counterparties", ["email"], unique=False)
    op.add_column("contracts", sa.Column("counterparty_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_contracts_counterparty_id", "contracts", "counterparties", ["counterparty_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contracts_counterparty_id", "contracts", type_="foreignkey")
    op.drop_column("contracts", "counterparty_id")
    op.drop_index("ix_counterparties_email", table_name="counterparties")
    op.drop_table("counterparties")
    # ### end Alembic commands ###
